import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    position: "absolute",
    zIndex: 1,
    paddingTop: 20,
    flex: 1,
    marginLeft: -15,
  },

  wrapper: {
    display: "flex",
    height: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingVertical: 120,
    flex: 1,
  },
  imgCont: {
    left: -100,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    justifyContent: "center",
    position: "absolute",
    maxWidth: "80%",
    maxHeight: 450,
    zIndex: 5,
  },
  img: {
    maxWidth: "80%",
    maxHeight: 450,
    resizeMode: "contain",
    zIndex: 8,
  },
  contentImg: {
    // flex: 1,
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginLeft: 20,
    zIndex: 2,
  },
  img1: {
    alignSelf: "flex-start",
    zIndex: 10,
  },
  img2: {
    alignSelf: "flex-start",
    marginLeft: 117,
    marginTop: -50,
    zIndex: 10,
  },
  img3: {
    alignSelf: "flex-start",
    marginLeft: 210,
    marginTop: -40,
    marginBottom: 20,
    zIndex: 0,
  },
  img4: {
    alignSelf: "flex-start",
    marginLeft: 240,
    marginBottom: 20,
    zIndex: 10,
  },
  img5: {
    alignSelf: "flex-start",
    marginLeft: 230,
    zIndex: 10,
  },
  img6: {
    alignSelf: "flex-start",
    marginLeft: 210,
    zIndex: 10,
  },
  img7: {
    alignSelf: "flex-start",
    marginLeft: 117,
    marginTop: 0,
    zIndex: 10,
  },
  img8: {
    alignSelf: "flex-start",
    marginTop: -30,
    zIndex: 10,
  },
});
